# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "public_network"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "i2b2db"
    vb.memory = 8192
    vb.cpus = 2
  end

  config.vm.provision :shell, :inline => 'echo "install script pending"'
end
