# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username = "ubuntu"

  config.vm.box_url = "http://54.93.194.56/vagrant/i2b2app.box"

  config.vm.box = "i2b2app"

  config.vm.network "public_network"

  config.vm.hostname = "i2b2app"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "i2b2app"
    vb.memory = 4096
    vb.cpus = 2
  end

  config.vm.provision :shell, :inline => "sudo apt-get -y install git; cd ~; git clone https://github.com/bp2014n2/i2b2.git; cd i2b2; sudo ./setup.sh core web;", privileged: false
  config.vm.provision :shell, :inline => "echo \"Machine reachable via `ifconfig eth1 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`\"", privileged: false
end
