# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.ssh.username = "ubuntu"

  config.vm.box_url = "http://54.93.194.56/vagrant/i2b2db.box"

  config.vm.box = "i2b2db"

  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = 2048
    vb.cpus = 1
  end

  config.vm.define "master", primary: true do |master|
    
    master.vm.hostname = "i2b2hpccm"

    master.vm.network "forwarded_port", guest: 8010, host: 8010
    master.vm.network "forwarded_port", guest: 8015, host: 8015

    master.vm.provider "virtualbox" do |vb|
      vb.name = "i2b2hpccm"
    end

    master.vm.provision "shell", path: "setup.sh"
    master.vm.provision :shell, :inline => "echo \"Machine reachable via `ifconfig eth1 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`\"", privileged: false

  end

  config.vm.define "worker1", autostart: false do |worker|
    
    worker.vm.hostname = "i2b2hpccw1"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "i2b2hpccw1"
    end

    worker.vm.provision :shell, :inline => "echo \"Machine reachable via `ifconfig eth1 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`\"", privileged: false

  end

  config.vm.define "worker2", autostart: false do |worker|
    
    worker.vm.hostname = "i2b2hpccw2"

    worker.vm.provider "virtualbox" do |vb|
      vb.name = "i2b2hpccw2"
    end

    worker.vm.provision :shell, :inline => "echo \"Machine reachable via `ifconfig eth1 | grep 'inet addr:' | cut -d: -f2| cut -d' ' -f1`\"", privileged: false

  end

end
